# Generated by Django 5.0.6 on 2024-05-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webversion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='year',
            old_name='semester',
            new_name='first_sem',
        ),
        migrations.AddField(
            model_name='year',
            name='second_sem',
            field=models.BooleanField(null=True),
        ),
    ]
