# Generated by Django 5.0.6 on 2024-05-25 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webversion', '0002_rename_semester_year_first_sem_year_second_sem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='year',
            name='second_sem',
        ),
    ]
