# Generated by Django 5.0.6 on 2024-05-25 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webversion', '0003_remove_year_second_sem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='year_group',
            field=models.IntegerField(default=1),
        ),
        migrations.RemoveField(
            model_name='course',
            name='semester',
        ),
        migrations.AddField(
            model_name='programme',
            name='semester',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Year',
        ),
    ]
