# Generated by Django 5.0.6 on 2024-05-25 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webversion', '0004_alter_programme_year_group_remove_course_semester_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programme',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='programme',
            name='year_group',
        ),
    ]
