# Generated by Django 5.0.6 on 2024-05-25 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webversion', '0005_remove_programme_semester_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='name',
        ),
    ]
