# Generated by Django 5.0.6 on 2024-05-25 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webversion', '0007_semester_course_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='programme',
        ),
        migrations.AddField(
            model_name='semester',
            name='programme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programme', to='webversion.programme'),
        ),
    ]
