# Generated by Django 5.0.6 on 2024-05-26 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webversion', '0008_remove_course_programme_semester_programme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='semester',
        ),
        migrations.AddField(
            model_name='course',
            name='programme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programme', to='webversion.programme'),
        ),
        migrations.DeleteModel(
            name='Semester',
        ),
    ]
