# Generated by Django 5.0.6 on 2024-05-26 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webversion', '0010_remove_course_lecturer_coursetolecturer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseToLecturer',
        ),
    ]
