# Generated by Django 5.0.6 on 2024-05-26 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webversion', '0013_remove_course_programme_course_programme1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lecturer1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lect1', to='webversion.lecturer'),
        ),
        migrations.AddField(
            model_name='course',
            name='lecturer10',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lect10', to='webversion.lecturer'),
        ),
        migrations.AddField(
            model_name='course',
            name='lecturer2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lect2', to='webversion.lecturer'),
        ),
        migrations.AddField(
            model_name='course',
            name='lecturer3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lect3', to='webversion.lecturer'),
        ),
        migrations.AddField(
            model_name='course',
            name='lecturer4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lect4', to='webversion.lecturer'),
        ),
        migrations.AddField(
            model_name='course',
            name='lecturer5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lect5', to='webversion.lecturer'),
        ),
        migrations.AddField(
            model_name='course',
            name='lecturer6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lect6', to='webversion.lecturer'),
        ),
        migrations.AddField(
            model_name='course',
            name='lecturer7',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lect7', to='webversion.lecturer'),
        ),
        migrations.AddField(
            model_name='course',
            name='lecturer8',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lect8', to='webversion.lecturer'),
        ),
        migrations.AddField(
            model_name='course',
            name='lecturer9',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lect9', to='webversion.lecturer'),
        ),
    ]
