# Generated by Django 5.0.6 on 2024-05-26 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webversion', '0018_remove_lecturer_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='course2',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='course3',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='course4',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='course5',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='programme1',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='programme2',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='programme3',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='programme4',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='programme5',
        ),
        migrations.AddField(
            model_name='lecturer',
            name='programme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programme', to='webversion.programme'),
        ),
    ]
