# Generated by Django 5.0.6 on 2024-05-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webversion', '0020_remove_lecturer_course1_lecturer_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
