# Generated by Django 5.0.6 on 2024-05-27 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webversion', '0021_alter_lecturer_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lecturer',
            new_name='Lecture',
        ),
    ]
