# Generated by Django 5.0.6 on 2024-05-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webversion', '0024_department_programme_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
