# Generated by Django 5.0.6 on 2024-05-27 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webversion', '0025_alter_department_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department', to='webversion.department'),
        ),
    ]
