# Generated by Django 5.0.6 on 2024-05-27 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webversion', '0026_alter_lecturer_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='fullname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
