# Generated by Django 5.0.6 on 2024-05-27 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webversion', '0028_remove_lecturer_fullname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='name',
        ),
    ]
