# Generated by Django 5.0.6 on 2024-05-30 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webversion', '0030_department_college'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15, null=True)),
                ('hours', models.PositiveSmallIntegerField()),
                ('has_labs', models.BooleanField(default=False)),
                ('lab_hours', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=255)),
                ('othernames', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Department1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='webversion.course1')),
            ],
        ),
        migrations.AddField(
            model_name='course1',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturer', to='webversion.lecturer1'),
        ),
    ]
