# Generated by Django 5.0.6 on 2024-05-30 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webversion', '0033_remove_department1_college_remove_course1_lecturer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='has_practicals',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='practical_hours',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
