# Generated by Django 5.0.6 on 2024-05-30 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webversion', '0034_course_has_practicals_course_practical_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_combined',
        ),
        migrations.AddField(
            model_name='course',
            name='lecturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alecturer', to='webversion.lecturer'),
        ),
        migrations.AddField(
            model_name='course',
            name='programme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aprogramme', to='webversion.programme'),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='has_labs',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='has_practicals',
            field=models.BooleanField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='hours',
            field=models.PositiveSmallIntegerField(default=2, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='lab_hours',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='practical_hours',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
    ]
