# Generated by Django 5.0.6 on 2024-05-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webversion', '0037_course_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='year_group',
        ),
        migrations.AddField(
            model_name='course',
            name='year_group',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
