# Generated by Django 5.0.6 on 2024-05-31 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webversion', '0039_schedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='duration',
            new_name='column',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='course_name',
            new_name='course',
        ),
        migrations.AddField(
            model_name='schedule',
            name='height',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='row',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
