# Generated by Django 5.0.6 on 2024-05-31 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webversion', '0040_rename_duration_schedule_column_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='somedepartment', to='webversion.department'),
        ),
    ]
