# Generated by Django 5.0.6 on 2024-06-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webversion', '0042_course_is_lab_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_electtive',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
