# Generated by Django 5.0.6 on 2024-06-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webversion', '0044_course_estimated_class_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='is_electtive',
            new_name='is_elective',
        ),
        migrations.AddField(
            model_name='location',
            name='is_Lab',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
