# Generated by Django 5.0.6 on 2024-06-01 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webversion', '0045_rename_is_electtive_course_is_elective_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_in_same_college',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
