# Generated by Django 5.0.6 on 2024-06-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webversion', '0046_location_is_in_same_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='day',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
