# Generated by Django 5.0.6 on 2024-06-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webversion', '0047_schedule_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='course_code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='year_group',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
