# Generated by Django 5.0.6 on 2024-06-10 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webversion', '0050_schedule_course_code_schedule_year_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='day',
        ),
        migrations.AddField(
            model_name='schedule',
            name='lecturer_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='location_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
