# Generated by Django 5.0.6 on 2024-06-11 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webversion', '0051_remove_schedule_day_schedule_lecturer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='lecturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='the_lecturer', to='webversion.lecturer'),
        ),
    ]
