# Generated by Django 5.0.6 on 2024-06-12 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webversion', '0052_schedule_lecturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='max_yg',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
