# Generated by Django 5.0.6 on 2024-06-12 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webversion', '0053_department_max_yg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
