# Generated by Django 5.0.6 on 2024-06-15 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webversion', '0056_course_is_comnined'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='is_comnined',
            new_name='is_combined',
        ),
    ]
