# Generated by Django 5.0.6 on 2024-06-20 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webversion', '0058_rename_has_practicals_course_is_contiguous_lab_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='max_yg',
            field=models.PositiveSmallIntegerField(default=4, null=True),
        ),
    ]
