# Generated by Django 5.0.6 on 2024-06-24 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webversion', '0060_location_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
