# Generated by Django 5.0.6 on 2024-07-02 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webversion', '0062_college_useraccount_department_college_main_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_creator', to='webversion.useraccount'),
        ),
        migrations.AddField(
            model_name='department',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_creator', to='webversion.useraccount'),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_creator', to='webversion.useraccount'),
        ),
        migrations.AddField(
            model_name='location',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_creator', to='webversion.useraccount'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_creator', to='webversion.useraccount'),
        ),
    ]
