# Generated by Django 5.0.6 on 2024-07-02 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webversion', '0063_course_creator_department_creator_lecturer_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=15),
        ),
    ]
