# Generated by Django 5.0.6 on 2024-07-04 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webversion', '0064_alter_course_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_college', to='webversion.college'),
        ),
    ]
