# Generated by Django 5.0.6 on 2024-07-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webversion', '0065_schedule_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='courses_per_day',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='telephone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
