# Generated by Django 5.0.6 on 2024-07-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webversion', '0066_college_courses_per_day_lecturer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='floor',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='time_preference',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
