# Generated by Django 5.0.6 on 2024-07-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webversion', '0067_lecturer_floor_lecturer_time_preference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='floor',
        ),
        migrations.AddField(
            model_name='location',
            name='floor',
            field=models.SmallIntegerField(null=True),
        ),
    ]
