# Generated by Django 5.0.6 on 2024-07-05 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webversion', '0068_remove_lecturer_floor_location_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='preferred_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_location', to='webversion.location'),
        ),
        migrations.AddField(
            model_name='department',
            name='limited',
            field=models.BooleanField(null=True),
        ),
    ]
