# Generated by Django 5.0.6 on 2024-07-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webversion', '0069_course_preferred_location_department_limited'),
    ]

    operations = [
        migrations.RenameField(
            model_name='college',
            old_name='courses_per_day',
            new_name='days_per_week',
        ),
        migrations.AddField(
            model_name='college',
            name='rows_per_day',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
