# Generated by Django 5.0.6 on 2024-07-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webversion', '0070_rename_courses_per_day_college_days_per_week_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='preferred_time',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
