# Generated by Django 5.0.6 on 2024-07-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webversion', '0071_course_preferred_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='preferred_day1',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='preferred_day2',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
