# Generated by Django 5.0.6 on 2024-07-10 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webversion', '0072_course_preferred_day1_course_preferred_day2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='preferred_day1',
        ),
        migrations.RemoveField(
            model_name='course',
            name='preferred_day2',
        ),
        migrations.RemoveField(
            model_name='course',
            name='preferred_location',
        ),
        migrations.RemoveField(
            model_name='course',
            name='preferred_time',
        ),
        migrations.CreateModel(
            name='Pref_day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_day', to='webversion.course')),
            ],
        ),
        migrations.CreateModel(
            name='Pref_location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_course', to='webversion.course')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_location', to='webversion.location')),
            ],
        ),
        migrations.CreateModel(
            name='Pref_time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_time', to='webversion.course')),
            ],
        ),
    ]
