# Generated by Django 5.0.6 on 2024-07-11 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webversion', '0073_remove_course_preferred_day1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pref_Stuff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.PositiveSmallIntegerField()),
                ('day', models.PositiveSmallIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pref_course', to='webversion.course')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_pref', to='webversion.useraccount')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pref_location', to='webversion.location')),
            ],
        ),
    ]
