# Generated by Django 5.0.6 on 2024-07-12 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webversion', '0074_pref_stuff'),
    ]

    operations = [
        migrations.AddField(
            model_name='pref_stuff',
            name='college_main',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pref_college', to='webversion.college'),
        ),
    ]
