# Generated by Django 4.2.14 on 2024-07-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webversion', '0075_pref_stuff_college_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='day',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='time',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
