# Generated by Django 4.2.14 on 2024-07-18 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webversion', '0077_schedule_batch_schedule_college_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='is_combined',
            new_name='is_contiguous_class_time',
        ),
    ]
