# Generated by Django 4.2.14 on 2024-07-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webversion', '0078_rename_is_combined_course_is_contiguous_class_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
