# Generated by Django 4.2.14 on 2024-07-21 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webversion', '0082_docs'),
    ]

    operations = [
        migrations.AddField(
            model_name='docs',
            name='pdf',
            field=models.FileField(null=True, upload_to='pdf'),
        ),
    ]
