# Generated by Django 4.2.14 on 2024-07-23 11:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webversion', '0083_docs_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('code', models.PositiveBigIntegerField()),
                ('posted', models.BooleanField(default=False)),
                ('batch', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='posted',
        ),
    ]
