# Generated by Django 4.2.14 on 2024-07-23 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webversion', '0084_timetable_remove_schedule_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='timetable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_timetable', to='webversion.timetable'),
        ),
    ]
