# Generated by Django 4.2.14 on 2024-07-23 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webversion', '0085_schedule_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='college_main',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='college_table', to='webversion.college'),
        ),
    ]
