# Generated by Django 4.2.14 on 2024-07-24 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webversion', '0087_remove_docs_batch_docs_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='code',
            field=models.CharField(max_length=20),
        ),
    ]
