# Generated by Django 4.2.14 on 2024-07-29 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webversion', '0088_alter_timetable_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='type',
            field=models.CharField(default='academic', max_length=255),
        ),
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('location_name', models.CharField(max_length=255)),
                ('lecturer_name', models.CharField(max_length=255)),
                ('time', models.PositiveSmallIntegerField()),
                ('day', models.PositiveSmallIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examcourse', to='webversion.timetable')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examlecturer', to='webversion.lecturer')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examlocation', to='webversion.location')),
            ],
        ),
    ]
