# Generated by Django 4.2.14 on 2024-07-30 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webversion', '0089_timetable_type_examschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='examschedule',
            name='creator_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examscreator', to='webversion.useraccount'),
        ),
    ]
