# Generated by Django 4.2.14 on 2024-07-30 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webversion', '0090_examschedule_creator_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examschedule',
            old_name='creator_id',
            new_name='creator',
        ),
    ]
