# Generated by Django 4.2.14 on 2024-07-30 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webversion', '0091_rename_creator_id_examschedule_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='examschedule',
            name='timetable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examtable', to='webversion.timetable'),
        ),
        migrations.AlterField(
            model_name='examschedule',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examcourse', to='webversion.course'),
        ),
    ]
