# Generated by Django 4.2.14 on 2024-07-30 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webversion', '0092_examschedule_timetable_alter_examschedule_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='examschedule',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examdept', to='webversion.department'),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='department_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
