# Generated by Django 4.2.14 on 2024-07-30 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webversion', '0094_examschedule_college_examschedule_college_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='examschedule',
            name='course_code',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
