# Generated by Django 4.2.14 on 2024-07-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webversion', '0095_examschedule_course_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='examschedule',
            name='size',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
