# Generated by Django 4.2.14 on 2024-07-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webversion', '0096_examschedule_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='exam_days',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='year_group',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
