# Generated by Django 4.2.14 on 2024-07-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webversion', '0097_college_exam_days_examschedule_year_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='exam_size',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
